
---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0
  linebreak-style: 0
